name: Set Up Genymotion Cloud Phone

on:
  push:
    branches:
      - main

jobs:
  setup-cloud-phone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Genymotion cloud phone setup
        run: |
          chmod +x setup_cloud_phone.sh
          ./setup_cloud_phone.sh
          
